const main = async () => {

}

main().catch((e) => {
    console.log(e);
    process.exit(1);
  });